version: '3'

services:
  db:
    container_name: maria
    image: mariadb:10.6.4
    environment:
      - MARIADB_DATABASE=spring
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"