version: '3'

services:
  db:
    container_name: maria-db
    image: mariadb:10.6.4
    environment:
      - MARIADB_DATABASE=spring
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  migration:
    image: flyway/flyway:8.0.4
    command: -configFiles=/flyway/conf/flyway.config -connectRetries=60 migrate
    volumes:
      - ./flyway/migration/main:/flyway/main
      - ./flyway/conf/develop.conf:/flyway/conf/flyway.config
    depends_on:
      - db
  admin:
    container_name: app-admin
    build: ./admin
    image: app-admin
    environment:
      - USER_PROFILE=${USER_PROFILE_DEVELOP}
    depends_on:
      - db
    ports:
      - "9090:8080"
  user:
    container_name: app-user
    build: ./user
    image: app-user
    environment:
      - USER_PROFILE=${USER_PROFILE_DEVELOP}
    depends_on:
      - db
    ports:
      - "8081:8080"