version: '3'

services:
  db:
    container_name: maria
    image: mariadb:10.6.4
    environment:
      - MARIADB_DATABASE=spring
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  admin:
    container_name: app-admin
    image: app-admin
    environment:
      - USER_PROFILE=${USER_PROFILE}
    depends_on:
      - db
    ports:
      - "9090:8080"
  user:
    container_name: app-user
    image: app-user
    environment:
      - USER_PROFILE=${USER_PROFILE}
    depends_on:
      - db
    ports:
      - "8081:8080"