spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/spring
    username: root
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3